#
dist: bionic
#
language: java
#
jdk:
  - openjdk8
  - openjdk11

# Install the rpmbuild tool we need.
before_install:
  - sudo apt-get install rpm

# We can skip the installation
# step, cause everything will be
# done in script script.
install: true

script: "mvn --show-version --errors --batch-mode -Prun-its clean verify"

cache:
    directories:
    - $HOME/.m2/repository

branches:
    except:
        - gh-pages
notifications:
    email:
        - khmarbaise@apache.org
        - dantran@apache.org
